# Generated by Django 3.0.6 on 2020-05-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='QQ',
            field=models.CharField(blank=True, default='NO', max_length=20, null=True),
        ),
    ]
