# Generated by Django 3.0.6 on 2020-05-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_customer_qq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='QQ',
        ),
    ]
