# Generated by Django 3.0.6 on 2020-05-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_country_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medicinelist',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
